{
 "title": "Metrics Application",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{service=\"metrics-app\"}[5m])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Error Rate Ratio (5 min average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sli:errors_per_request:ratio_rate5m{job=\"metrics-app\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Average Reponse Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{service=\"metrics-app\"}[5m])/rate(http_request_duration_seconds_count{service=\"metrics-app\"}[5m])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "90%ile Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, http_request_duration_seconds_bucket{job=\"metrics-app\"})",
     "legendFormat": "{{ code}}"
    }
   ]
  },
  {
   "title": "99%ile Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, http_request_duration_seconds_bucket{job=\"metrics-app\"})",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Response Time Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}